<?php // Generated by CuyZ\Valinor\Cache\FileSystemCache
return fn () => array (
  'D:\\Personal\\Proyectos\\Desarrollo\\sofit-gym\\vendor\\cuyz\\valinor\\src\\Mapper\\Object\\DynamicConstructor.php' => 1782672820,
);
