<?php // Generated by CuyZ\Valinor\Cache\FileSystemCache
return fn () => new \CuyZ\Valinor\Definition\ClassDefinition(
    'App\\Models\\BitacoraDTO',
    new CuyZ\Valinor\Type\Types\NativeClassType('App\Models\BitacoraDTO', []),
    CuyZ\Valinor\Definition\Attributes::empty(),
    new \CuyZ\Valinor\Definition\Properties(new \CuyZ\Valinor\Definition\PropertyDefinition(
    'id_bitacora',
    'App\Models\BitacoraDTO::$id_bitacora',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'id_usuario',
    'App\Models\BitacoraDTO::$id_usuario',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'nombre_usuario',
    'App\Models\BitacoraDTO::$nombre_usuario',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'id_modulo',
    'App\Models\BitacoraDTO::$id_modulo',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'modulo',
    'App\Models\BitacoraDTO::$modulo',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'accion',
    'App\Models\BitacoraDTO::$accion',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'mensaje',
    'App\Models\BitacoraDTO::$mensaje',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'nivel',
    'App\Models\BitacoraDTO::$nivel',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'contexto',
    'App\Models\BitacoraDTO::$contexto',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'datos_previos',
    'App\Models\BitacoraDTO::$datos_previos',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'datos_nuevos',
    'App\Models\BitacoraDTO::$datos_nuevos',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\PropertyDefinition(
    'fecha',
    'App\Models\BitacoraDTO::$fecha',
    new CuyZ\Valinor\Type\Types\UnionType(new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeImmutable', []), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeImmutable', []), CuyZ\Valinor\Type\Types\NullType::get()),
    false,
    NULL,
    true,
    CuyZ\Valinor\Definition\Attributes::empty()
)),
    new \CuyZ\Valinor\Definition\Methods(new \CuyZ\Valinor\Definition\MethodDefinition(
    '__construct',
    'App\Models\BitacoraDTO::__construct()',
    CuyZ\Valinor\Definition\Attributes::empty(),
    new \CuyZ\Valinor\Definition\Parameters(new \CuyZ\Valinor\Definition\ParameterDefinition(
    'id_bitacora',
    'App\Models\BitacoraDTO::__construct($id_bitacora)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'id_usuario',
    'App\Models\BitacoraDTO::__construct($id_usuario)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'nombre_usuario',
    'App\Models\BitacoraDTO::__construct($nombre_usuario)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'id_modulo',
    'App\Models\BitacoraDTO::__construct($id_modulo)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'modulo',
    'App\Models\BitacoraDTO::__construct($modulo)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'accion',
    'App\Models\BitacoraDTO::__construct($accion)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'mensaje',
    'App\Models\BitacoraDTO::__construct($mensaje)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'nivel',
    'App\Models\BitacoraDTO::__construct($nivel)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'contexto',
    'App\Models\BitacoraDTO::__construct($contexto)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'datos_previos',
    'App\Models\BitacoraDTO::__construct($datos_previos)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'datos_nuevos',
    'App\Models\BitacoraDTO::__construct($datos_nuevos)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'fecha',
    'App\Models\BitacoraDTO::__construct($fecha)',
    new CuyZ\Valinor\Type\Types\UnionType(new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeImmutable', []), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeImmutable', []), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
)),
    false,
    true,
    CuyZ\Valinor\Type\Types\MixedType::get()
)),
    false,
    false,
);
