<?php // Generated by CuyZ\Valinor\Cache\FileSystemCache
return fn () => new \CuyZ\Valinor\Definition\ClassDefinition(
    'DateTimeImmutable',
    new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeImmutable', []),
    CuyZ\Valinor\Definition\Attributes::empty(),
    new \CuyZ\Valinor\Definition\Properties(),
    new \CuyZ\Valinor\Definition\Methods(new \CuyZ\Valinor\Definition\MethodDefinition(
    '__construct',
    'DateTimeImmutable::__construct()',
    CuyZ\Valinor\Definition\Attributes::empty(),
    new \CuyZ\Valinor\Definition\Parameters(new \CuyZ\Valinor\Definition\ParameterDefinition(
    'datetime',
    'DateTimeImmutable::__construct($datetime)',
    CuyZ\Valinor\Type\Types\NativeStringType::get(),
    CuyZ\Valinor\Type\Types\NativeStringType::get(),
    true,
    false,
    'now',
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'timezone',
    'DateTimeImmutable::__construct($timezone)',
    new CuyZ\Valinor\Type\Types\UnionType(new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeZone', []), CuyZ\Valinor\Type\Types\NullType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeZone', []), CuyZ\Valinor\Type\Types\NullType::get()),
    true,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
)),
    false,
    true,
    CuyZ\Valinor\Type\Types\MixedType::get()
)),
    false,
    false,
);
