<?php // Generated by CuyZ\Valinor\Cache\FileSystemCache
return fn () => new \CuyZ\Valinor\Definition\ClassDefinition(
    'CuyZ\\Valinor\\Mapper\\Object\\DynamicConstructor',
    new CuyZ\Valinor\Type\Types\NativeClassType('CuyZ\Valinor\Mapper\Object\DynamicConstructor', []),
    CuyZ\Valinor\Definition\Attributes::empty(),
    new \CuyZ\Valinor\Definition\Properties(),
    new \CuyZ\Valinor\Definition\Methods(),
    true,
    false,
);
