<?php // Generated by CuyZ\Valinor\Cache\FileSystemCache
return fn () => new \CuyZ\Valinor\Definition\FunctionDefinition(
    '__invoke',
    'CuyZ\Valinor\Mapper\Object\DateTimeFormatConstructor::__invoke()',
    new \CuyZ\Valinor\Definition\Attributes(new \CuyZ\Valinor\Definition\AttributeDefinition(
    new \CuyZ\Valinor\Definition\ClassDefinition(
    'CuyZ\\Valinor\\Mapper\\Object\\DynamicConstructor',
    new CuyZ\Valinor\Type\Types\NativeClassType('CuyZ\Valinor\Mapper\Object\DynamicConstructor', []),
    CuyZ\Valinor\Definition\Attributes::empty(),
    new \CuyZ\Valinor\Definition\Properties(),
    new \CuyZ\Valinor\Definition\Methods(),
    true,
    false,
),
    [],
    array (
  0 => 'closure',
),
    0,
)),
    'D:\\Personal\\Proyectos\\Desarrollo\\sofit-gym\\vendor\\cuyz\\valinor\\src\\Mapper\\Object\\DateTimeFormatConstructor.php',
    'CuyZ\\Valinor\\Mapper\\Object\\DateTimeFormatConstructor',
    false,
    false,
    new \CuyZ\Valinor\Definition\Parameters(new \CuyZ\Valinor\Definition\ParameterDefinition(
    'className',
    'CuyZ\Valinor\Mapper\Object\DateTimeFormatConstructor::__invoke($className)',
    new CuyZ\Valinor\Type\Types\ClassStringType([new CuyZ\Valinor\Type\Types\NativeClassType('DateTime', []), new CuyZ\Valinor\Type\Types\NativeClassType('DateTimeImmutable', [])]),
    CuyZ\Valinor\Type\Types\NativeStringType::get(),
    false,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
), new \CuyZ\Valinor\Definition\ParameterDefinition(
    'value',
    'CuyZ\Valinor\Mapper\Object\DateTimeFormatConstructor::__invoke($value)',
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NonEmptyStringType::get(), CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NativeFloatType::get()),
    new CuyZ\Valinor\Type\Types\UnionType(CuyZ\Valinor\Type\Types\NativeStringType::get(), CuyZ\Valinor\Type\Types\NativeIntegerType::get(), CuyZ\Valinor\Type\Types\NativeFloatType::get()),
    false,
    false,
    NULL,
    CuyZ\Valinor\Definition\Attributes::empty()
)),
    new CuyZ\Valinor\Type\Types\InterfaceType('DateTimeInterface', [])
);
